version: '3.3'

services:
  mongodb:
    image: mongo
    container_name: "mongodb"
    networks:
      - polygon
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongodata:/data/db
    ports:
      - 27017:27017
  
  myapp:
    build: .
    networks:
      - polygon
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/usr/lib/app
    ports:
      - 3000:3000
    depends_on:
      - mongodb

networks:
  polygon:
    external:
      name: "polygon-network"

volumes:
  mongodata: